config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

   root 'static_pages#index'

   resources :static_pages
   resources :posts
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'posts/page/:pagenumber' => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :body, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  mount_uploader :image, ImagesUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :main_blog_picture, MainBlogPictureUploader
  has_many :images
  has_many :comments
  has_many :users
  accepts_nested_attributes_for :images

  validates :facebook, presence: true
  validates :twitter, presence: true
  validates :googlePlus, presence: true
  validates :pinterest, presence: true
  validates :email, presence: true
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.email     = auth.info.email
      user.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @pagenumber = params[:pagenumber].to_i
    if params[:pagenumber] == nil
      @pagenumber = 1
    end
    if Post.all.length % 5 != 0 && @pagenumber == (Post.all.length/5.0).floor + 1 && @pagenumber != 1
      @pagenation = "newer"
      @posts = Post.order("created_at")[0.. (Post.all.length % 5) - 1]
    elsif Post.all.length - (5*@pagenumber) > -1
      @posts = Post.order("created_at")[Post.all.length - 5*@pagenumber..(Post.all.length - 5*@pagenumber) + 5]
      if @pagenumber == 1
        if Post.all.length - (5*@pagenumber) > 0
          @pagenation = "older"
        else
          @pagenation = ""
        end
      else
        @pagenation = "newerolder"
      end
    elsif @pagenumber == 1
      @pagenation = ""
      @posts = Post.order("created_at")
    end

      @timezone = 'Eastern Time (US & Canada)'
  end
  def show
    @styleSheet = "posts"
      @timezone = 'Eastern Time (US & Canada)'
    @post = Post.find(params[:id])
    @comments = @post.comments
    cookies[:lastPostId] = @post.id
  end

  def create
    @styleSheet = "posts"
    if post_params[:key] == "LOPITS56"
      @post = Post.new(post_params)
      if @post.save
        redirect_to post_url(@post)
      end
    end
  end

  def new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if post_params[:key] == "LOPITS56"
      if @post.update_attributes(post_params)
      redirect_to post_url(@post)
      end
    elsif  post_params[:key] == nil && current_user != nil
      @comments = @post.comments.build
      @comments.update_attributes(:user_id => current_user.id)
      @comments.update_attributes(:body => post_params[:comments][:body])
      redirect_to post_url(@post)
    end
  end

    private
    def post_params
      params.require(:post).permit(:key, :author, :body, :title, :main_blog_picture, :twitter, :facebook, :googlePlus, :pinterest, :email, comments: [:body])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    if cookies[:lastPostId] != nil
      redirect_to post_path(cookies[:lastPostId])
    else
      redirect_to post_path
    end
  end

  def destroy
    session[:user_id] = nil
    if cookies[:lastPostId] != nil
      redirect_to post_path(cookies[:lastPostId])
    else
      redirect_to post_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    greetingList = ["Hia","Howdy", "Hey", "Welcome", "Konichiwa", "Yo", "Greetings", "Hello", "Salutations","Ní hâo",
    "Bonjour"]
    @greeting = greetingList[rand(0..10)]
    @styleSheet = "static_pages"
    @staticPage = StaticPage.new()
  end

  def create
    @staticPage = StaticPage.new(static_pages_params)
    if @staticPage.save
      StaticPages.job(@staticPage).deliver_now
      redirect_to root_url
    end
  end

  private
  def static_pages_params
    params.require(:static_page).permit(:name, :email, :phone, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
    @markdown.render(content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="p:domain_verify" content="f6b8ce2ac6069939c8886874ed4ad27d"/>
  <meta name="msvalidate.01" content="53470898C21F5DC8E8C7C83E9300D4BA" />
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script src="http://az756089.vo.msecnd.net/offwhitecdn/animatescroll.min.js"></script>

  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= yield %>
</body>
</html>

app/views/posts/_comments.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="marginContainer comment">
      <p><%=comment.body%><br>      -<span class="authorName"> <%=User.find(comment.user_id).name%></span> at <%=comment.created_at.in_time_zone(@timezone).strftime("%l:%M %p %Z - %b %d %Y ")%>
      </p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 editPost">
      <h1 class="green">Edit a Post</h1>
      <%= form_for @post, url: {action: 'update'}, html: {class: "verticalForm"} do |f| %>
          <%= f.text_field :title, :value => @post.title %><br>
          <%= f.file_field :main_blog_picture %>
          <%= f.text_field :author, :value => @post.author %><br>
          <%= f.text_area :body, :value => @post.body, :class => "bigTextarea" %><br>
          <%= f.text_field :twitter, :value => "Twitter" %><br>
          <%= f.text_field :facebook, :value => "Facebook" %><br>
          <%= f.text_field :googlePlus, :value => "Google Plus" %><br>
          <%= f.text_field :pinterest, :value => "Pinterest" %><br>
          <%= f.text_field :email, :value => "Email" %><br>
          <%= f.text_field :key, :value => "Password" %><br>
          <%= f.submit "Submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<head lang="en">
  <title>Blog | Offf White Web Design,  Harrisburg PA</title>
  <meta name="description" content="The Blog of Offwhite Web Design, a small and simple web design company. Specializing in pretty sites and originality. Based out of Harrisburg PA.">
</head>
<nav class="navbar navbar-default hideDesktop navbar-fixed-top" id="mobileNav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" id="navToggleMobile" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path%>#work">Work</a></li>
        <li><a href="<%= root_path%>#connect">Connect</a></li>
        <li><%= link_to "Blog", posts_path%></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">

  <div class=" row navbar navbar-default navbar-top blogNav hideMobile" id="nav">
    <div class="col-lg-12">
      <ul>
        <li id="homeLi"><a href="<%=root_path%>"><img id="navLogo" alt="Off White, Off White Web Design's Logo" src="http://az756089.vo.msecnd.net/offwhitecdn/square.svg"></a></li>

      </ul><br>
      <ul id="linksList">
        <li><a href="<%=root_path%>#work" >Work</a></li>
        <li><a href="<%=root_path%>#connect" >Connect</a></li>
        <li><a href="<%=posts_path%>" >Blog</a></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <a href="<%=root_path%>"><img id="mobileLogo" class="hideDesktop" alt="Off White, Off White Web Design's Logo" src="http://az756089.vo.msecnd.net/offwhitecdn/square.svg"></a>
  </div>
    <%= render partial: "posts", collection: @posts, as: :post %>
  <div class="row">
        <div class="col-md-12">
          <nav>
            <ul class="pager">
              <%if @pagenation == "older" || @pagenation == "newerolder"%>
                <li class="pagenation"><a  href="<%=posts_path%>/page/<%= @pagenumber + 1%>">Older</a></li>
              <%end%>
              <%if @pagenation == "newer" || @pagenation == "newerolder"%>
                      <li class="pagenation"><a  href="<%=posts_path%>/page/<%= @pagenumber - 1%>">Newer</a></li>
              <%end%>
            </ul>
          </nav>
      </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 createPost">
      <h1 class="green">Form a New Post</h1>
      <%= form_for Post.new(), url: {action: 'create'}, html: {class: "verticalForm"} do |f| %>
          <%= f.text_field :title, :value => "Title" %><br>
          <%= f.file_field :main_blog_picture %>
          <%= f.text_field :author, :value => "Author" %><br>
          <%= f.text_area :body, :value => "Post", :class => "bigTextarea" %><br>
          <%= f.text_field :twitter, :value => "Twitter" %><br>
          <%= f.text_field :facebook, :value => "Facebook" %><br>
          <%= f.text_field :googlePlus, :value => "Google Plus" %><br>
          <%= f.text_field :pinterest, :value => "Pinterest" %><br>
          <%= f.text_field :email, :value => "Email" %><br>
          <%= f.text_field :key, :value => "Password" %><br>
          <%= f.submit "Submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<head>
  <title><%=@post.title%> | Offf White Web Design,  Harrisburg PA | UI/UX Website Design and Development</title>
  <meta name="description" content="<%= @post.body[0..500] %>...">
  <link rel="image_src" href="<%=@post.main_blog_picture.url%>" />
  <meta property='og:image' content='<%=@post.main_blog_picture.url%>'/>

</head>
<nav class="navbar navbar-default hideDesktop navbar-fixed-top" id="mobileNav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" id="navToggleMobile" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path%>#work">Work</a></li>
        <li><a href="<%= root_path%>#connect">Connect</a></li>
        <li><%= link_to "Blog", posts_path%></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fuild">
  <div class="row">
    <a href="<%=root_url%>"><img id="mobileLogo" class="hideDesktop showMobileLogo" alt="Off White, Off White Web Design's Logo" src="http://az756089.vo.msecnd.net/offwhitecdn/square.svg"></a>
  </div>
  <div class="row" >
    <div class="col-xs-12">
      <div class=" row navbar navbar-default navbar-top blogNav" id="nav">
        <div class="col-lg-12">
          <ul>
            <li  id="homeLi" class=noBorder"><a  href="<%=root_path%>"><img id="navLogo" alt="Off White, Off White Web Design's Logo" src="http://az756089.vo.msecnd.net/offwhitecdn/square.svg"></a></li>
          </ul><br>
          <ul id="linksList">
            <li><a href="<%=root_path%>#work" >Work</a></li>
            <li><a href="<%=root_path%>#connect" >Connect</a></li>
            <li><a href="<%=posts_path%>" >Blog</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-8 col-md-offset-2 pink postInfo showPostInfo">
      <h1 class="postTitle"><%= @post.title %></h1>

      <div class="author" id="imageTrigger">by <span class="authorName"><%= @post.author %></span>, published at <span class="authorName"><%= @post.created_at.in_time_zone(@timezone).strftime("%l:%M %p %Z - %b %d %Y ") %></span></div>
        <ul class="socialMediaPost"><a href="<%=@post.facebook%>" target="_blank">
          <li>
            <svg version="1.1" id="Capa_1" class="icon" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                 width="512px" height="512px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
              <g>
                <path d="M296.296,512H200.36V256h-64v-88.225l64-0.029l-0.104-51.976C200.256,43.794,219.773,0,304.556,0h70.588v88.242h-44.115
                            c-33.016,0-34.604,12.328-34.604,35.342l-0.131,44.162h79.346l-9.354,88.225L296.36,256L296.296,512z"/>
              </g>
            </svg>
          </li></a>
          <a href="<%=@post.twitter%>" target="_blank">
          <li>
            <svg version="1.1" id="Capa_1" class="icon" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                 viewBox="0 0 612 612" style="enable-background:new 0 0 612 612;" xml:space="preserve">
              <g>
                <g>
                  <path d="M612,116.258c-22.525,9.981-46.694,16.75-72.088,19.772c25.929-15.527,45.777-40.155,55.184-69.411
                                c-24.322,14.379-51.169,24.82-79.775,30.48c-22.907-24.437-55.49-39.658-91.63-39.658c-69.334,0-125.551,56.217-125.551,125.513
                                c0,9.828,1.109,19.427,3.251,28.606C197.065,206.32,104.556,156.337,42.641,80.386c-10.823,18.51-16.98,40.078-16.98,63.101
                                c0,43.559,22.181,81.993,55.835,104.479c-20.575-0.688-39.926-6.348-56.867-15.756v1.568c0,60.806,43.291,111.554,100.693,123.104
                                c-10.517,2.83-21.607,4.398-33.08,4.398c-8.107,0-15.947-0.803-23.634-2.333c15.985,49.907,62.336,86.199,117.253,87.194
                                c-42.947,33.654-97.099,53.655-155.916,53.655c-10.134,0-20.116-0.612-29.944-1.721c55.567,35.681,121.536,56.485,192.438,56.485
                                c230.948,0,357.188-191.291,357.188-357.188l-0.421-16.253C573.872,163.526,595.211,141.422,612,116.258z"/>
                </g>
              </g>

            </svg>
          </li></a>
          <a href="<%=@post.googlePlus%>" target="_blank">
          <li>
            <svg version="1.1" id="Capa_1" class="icon" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                 width="96.828px" height="96.827px" viewBox="0 0 96.828 96.827" style="enable-background:new 0 0 96.828 96.827;"
                 xml:space="preserve">
              <g>
                <g>
                  <path d="M62.617,0H39.525c-10.29,0-17.413,2.256-23.824,7.552c-5.042,4.35-8.051,10.672-8.051,16.912
                                c0,9.614,7.33,19.831,20.913,19.831c1.306,0,2.752-0.134,4.028-0.253l-0.188,0.457c-0.546,1.308-1.063,2.542-1.063,4.468
                                c0,3.75,1.809,6.063,3.558,8.298l0.22,0.283l-0.391,0.027c-5.609,0.384-16.049,1.1-23.675,5.787
                                c-9.007,5.355-9.707,13.145-9.707,15.404c0,8.988,8.376,18.06,27.09,18.06c21.76,0,33.146-12.005,33.146-23.863
                                c0.002-8.771-5.141-13.101-10.6-17.698l-4.605-3.582c-1.423-1.179-3.195-2.646-3.195-5.364c0-2.672,1.772-4.436,3.336-5.992
                                l0.163-0.165c4.973-3.917,10.609-8.358,10.609-17.964c0-9.658-6.035-14.649-8.937-17.048h7.663c0.094,0,0.188-0.026,0.266-0.077
                                l6.601-4.15c0.188-0.119,0.276-0.348,0.214-0.562C63.037,0.147,62.839,0,62.617,0z M34.614,91.535
            c-13.264,0-22.176-6.195-22.176-15.416c0-6.021,3.645-10.396,10.824-12.997c5.749-1.935,13.17-2.031,13.244-2.031
            c1.257,0,1.889,0,2.893,0.126c9.281,6.605,13.743,10.073,13.743,16.678C53.141,86.309,46.041,91.535,34.614,91.535z
            M34.489,40.756c-11.132,0-15.752-14.633-15.752-22.468c0-3.984,0.906-7.042,2.77-9.351c2.023-2.531,5.487-4.166,8.825-4.166
            c10.221,0,15.873,13.738,15.873,23.233c0,1.498,0,6.055-3.148,9.22C40.94,39.337,37.497,40.756,34.489,40.756z"/>
                  <path d="M94.982,45.223H82.814V33.098c0-0.276-0.225-0.5-0.5-0.5H77.08c-0.276,0-0.5,0.224-0.5,0.5v12.125H64.473
                                c-0.276,0-0.5,0.224-0.5,0.5v5.304c0,0.275,0.224,0.5,0.5,0.5H76.58V63.73c0,0.275,0.224,0.5,0.5,0.5h5.234
                                c0.275,0,0.5-0.225,0.5-0.5V51.525h12.168c0.276,0,0.5-0.223,0.5-0.5v-5.302C95.482,45.446,95.259,45.223,94.982,45.223z"/>
                </g>
              </g>

            </svg>
          </li></a>
          <a href="<%=@post.pinterest%>" target="_blank">
          <li>
            <svg version="1.1" class="icon" id="Capa_1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                 width="533.333px" height="533.333px" viewBox="0 0 533.333 533.333" style="enable-background:new 0 0 533.333 533.333;"
                 xml:space="preserve">
              <g>
                <path d="M266.667,0C119.391,0,0,119.391,0,266.667c0,147.275,119.388,266.666,266.667,266.666
                            c147.275,0,266.667-119.391,266.667-266.666C533.333,119.391,413.942,0,266.667,0z M292.523,356.311
                            c-24.229-1.882-34.397-13.883-53.388-25.421c-10.448,54.781-23.21,107.302-61.01,134.734
                            c-11.669-82.795,17.132-144.981,30.505-210.997c-22.804-38.389,2.744-115.643,50.844-96.601
                            c59.18,23.41-51.25,142.712,22.881,157.613c77.406,15.556,109.004-134.302,61.011-183.035
                            c-69.354-70.367-201.874-1.604-185.578,99.144c3.966,24.631,29.412,32.103,10.168,66.095c-44.385-9.839-57.63-44.845-55.925-91.517
                            c2.744-76.393,68.638-129.877,134.733-137.274c83.584-9.356,162.035,30.681,172.867,109.311
                            C431.826,267.107,381.899,363.223,292.523,356.311z"/>
              </g>

            </svg>
          </li></a>
          <a href="<%=@post.email%>" target="_blank">
          <li>
            <svg version="1.1" class=" icon" id="Capa_1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                 width="479.916px" height="479.916px" viewBox="0 0 479.916 479.916" style="enable-background:new 0 0 479.916 479.916;"
                 xml:space="preserve">
              <g>
                <path d="M12.5,408.458h454.916c6.903,0,12.5-5.596,12.5-12.5V144.772v-7.855V83.958c0-6.904-5.597-12.5-12.5-12.5H12.5
                                c-6.903,0-12.5,5.596-12.5,12.5v52.959v7.855v251.186C0,402.862,5.597,408.458,12.5,408.458z M454.916,383.458H25V157.062
                                l209.408,103.773c3.496,1.732,7.604,1.732,11.1,0l209.408-103.773V383.458z M454.916,96.458v32.703L239.958,235.684L25,129.161
                                V96.458H454.916z"/>
              </g>

            </svg>
          </li></a>
        </ul>
      </div>
    </div>

  <div class="row" id="body">
    <div class="col-md-6 col-md-offset-3">
      <div class="marginContainer" id="backgroundTrig">
      <div><%= markdown(@post.body).html_safe %></div>
      </div>
    </div>
  </div>
</div>
<div class="row marginRow">
  <div class="col-md-8 col-md-offset-2">
    <div class="clearMargin">
    <h1 id="commments">Comments</h1>
    </div>
    </div>
  </div>
<%= render partial: "comments", collection: @comments, as: :comment %>
    <div class="row marginRow">
      <div class="col-md-8 col-md-offset-2 black" id="postComment">
          <% if current_user %>
              <%= form_for @post, url: {action: 'update'}, html: {class: "verticalForm"} do |f| %>
                  <%= f.fields_for :comments do |builder| %>
                      <%= builder.text_area :body, :class => "commentTextarea", :value=> "Comment" %>
                  <% end %><br>
                  <%= f.submit "Submit" %><br>
                  Signed in as <strong><%= current_user.name%> </strong><%= link_to "Log out", signout_path, id: "sign_out" %>
        <% end %>
          <% else %>
              <%= link_to "Log in to Add a Comment", "/auth/google_oauth2", id: "sign_in" %>
          <% end %>
        </div>
    </div>

</div>

<img id="mainImage" src="<%=@post.main_blog_picture.url%>">

app/views/static_pages/job.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<h2><%= @staticPage.name %></h2>
<h2><%= @staticPage.email %></h2>
<h2><%= @staticPage.phone %></h2>
<p><%= @staticPage.description %></p>
</body>
</html>